import React, { useState } from 'react';
import { ChevronDownIcon } from '@heroicons/react/24/outline'; // Updated import

const FAQItem = ({ question, answer }) => {
     const [isOpen, setIsOpen] = useState(false);

     return (
          <div
               onClick={() => setIsOpen(!isOpen)}
               className="relative bg-[#fdfdfd] border border-[#a6a6a6] rounded-lg p-6 flex items-start justify-between gap-4 mb-4 cursor-pointer"
          >
               <div className="flex-1">
                    <h3 className="font-medium text-lg">{question}</h3>
                    {isOpen && <p className="text-gray-600 mt-2">{answer}</p>}
               </div>
               <button
                    className="flex items-center justify-center h-[2rem] w-[2rem] rounded-full bg-transparent"
               >
                    <ChevronDownIcon className={`w-6 h-6 transition-transform ${isOpen ? 'rotate-180' : ''}`} />
               </button>
          </div>
     );
};

const FAQSection = () => {
     return (
          <div className=" mx-auto p-8 bg-white shadow-lg rounded-lg">
               <div className="text-center mb-6 border-[2px] border-[#a6a6a6] mt-4 shadow-xl rounded-lg py-4">
                    <h2 className="text-3xl font-bold mb-4 mt-2">Frequently Asked Questions</h2>
                    <div className="text-gray-400 text-lg mt-4 mb-1">Your Queries Answered</div>
               </div>
               <div>
                    <FAQItem
                         question="What is an NFC card and how does it work?"
                         answer="Programming your NFC card is easy. Simply use an NFC-enabled smartphone or device, download a compatible app, and follow the instructions to write data."
                    />
                    <FAQItem
                         question="How can I program my NFC card?"
                         answer="Programming your NFC card is easy. Simply use an NFC-enabled smartphone or device, download a compatible app, and follow the instructions to write data."
                    />
                    <FAQItem
                         question="Are NFC cards secure for payment transactions?"
                         answer="Yes, NFC cards are highly secure for payment transactions. They use encryption and secure channels to protect your data."
                    />
                    <FAQItem
                         question="Can NFC cards be customized with my design?"
                         answer="Absolutely! We offer customization services so you can have NFC cards with your unique design, logo, and branding."
                    />
                    <FAQItem
                         question="What is the range of an NFC card?"
                         answer="NFC cards typically have a range of about 4 centimeters. This proximity ensures secure and intentional interactions."
                    />
                    <FAQItem
                         question="Do NFC cards require batteries?"
                         answer="No, NFC cards do not require batteries. They are powered by the electromagnetic field generated by the NFC reader."
                    />
               </div>
          </div>
     );
};

export default FAQSection;
